/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs203.project04;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        
        
        System.out.println("Hello");
    }
}
